name: brick_breaker
description: "Walking through Flutter Team's Codelab: Introduction to Flame with Flutter (Re-implementing Woz's Breakout) https://codelabs.developers.google.com/codelabs/flutter-flame-brick-breaker"

publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flame: ^1.26.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
